<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Capital' => '',
    'Cities' => 'Cidades',
    'City' => 'Cidade',
    'Code' => '',
    'Code2' => '',
    'Continent' => '',
    'Countries' => 'Países',
    'Country' => 'País',
    'Country Code' => '',
    'Create' => 'Cadastrar',
    'Create City' => '',
    'Create Country' => '',
    'Create {modulo}' => 'Cadastrar {modulo}',
    'Delete' => '',
    'District' => '',
    'Gnp' => '',
    'Gnpold' => '',
    'Government Form' => '',
    'Head Of State' => '',
    'ID' => '',
    'Indep Year' => '',
    'Is Official' => '',
    'Language' => '',
    'Life Expectancy' => '',
    'Local Name' => '',
    'Name' => 'Nome',
    'Percentage' => '',
    'Population' => '',
    'Region' => '',
    'Reset' => '',
    'Search' => '',
    'Surface Area' => '',
    'Update' => 'Alterar',
    'Update {modelClass}: ' => '',
    'Africa'=> 'África',
    'Antarctica'=>'Antártida',
    'Asia'=>'Ásia',
    'Europe'=>'Europa',
    'North America'=>'América do Norte',
    'Oceania'=>'Oceania',
    'South America'=>'América do Sul',
    'Countries of '=>'Países da ',
    'Submit' => 'Enviar',
    ''
];